// API endpoint that returns random healthy tips quotes as raw string

const animeQuotes = [
  "“It’s not the face that makes someone a monster, it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“It’s not the power of the curse… it’s the power you give the curse.” – Naruto Uzumaki",
  "“When you have to save someone you love, it’s okay to feel weak.” – Erza Scarlet",
  "“I’m not gonna die in a place like this. The world is too big. I’m gonna continue my journey!” – Monkey D. Luffy",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“No matter how deep the night, it always turns to day, eventually.” – Brook",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rin Tohsaka",
  "“If you feel yourself hitting up against your limit, remember for what cause you clench your fists… remember why you started down this path, and let that memory carry you beyond your limit.” – Izuku Midoriya",
  "“I’m not a weapon of mass destruction; I’m a hero who’ll blast you!” – Bakugo Katsuki",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“I don’t want to be someone’s reason for unhappiness. I want to be a reason for someone’s happiness.” – Rokuro Enmado",
  "“People die if they are killed.” – Shirou Emiya",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“I’m not a weapon of mass destruction; I’m a hero who’ll blast you!” – Bakugo Katsuki",
  "“The moment you give up is the moment you let someone else win.” – Kakashi Hatake",
  "“No matter how deep the night, it always turns to day, eventually.” – Brook",
  "“When you have to save someone you love, it’s okay to feel weak.” – Erza Scarlet",
  "“I’m not gonna die in a place like this. The world is too big. I’m gonna continue my journey!” – Monkey D. Luffy",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rin Tohsaka",
  "“If you feel yourself hitting up against your limit, remember for what cause you clench your fists… remember why you started down this path, and let that memory carry you beyond your limit.” – Izuku Midoriya",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“I don’t want to be someone’s reason for unhappiness. I want to be a reason for someone’s happiness.” – Rokuro Enmado",
  "“People die if they are killed.” – Shirou Emiya",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“Don’t be so quick to throw away your life. No matter how disgraceful or embarrassing it may be, you need to keep struggling to find your way out until the very end.” – Clare",
  "“There’s no point in running away from things that make you sad.” – Gintoki Sakata",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“People’s lives don’t end when they die. It ends when they lose faith.” – Itachi Uchiha",
  "“In this world, whenever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.” – Lelouch Lamperouge",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome Higurashi",
  "“A lesson without pain is meaningless, for you cannot gain something without sacrificing something else in return.” – Edward Elric",
  "“Even if I’m weak, I’ll keep fighting. Until the end, I’ll keep fighting.” – Allen Walker",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“I’ll take a potato chip… and eat it!” – Light Yagami",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“I don’t want to be someone’s reason for unhappiness. I want to be a reason for someone’s happiness.” – Rokuro Enmado",
  "“People die if they are killed.” – Shirou Emiya",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“Don’t be so quick to throw away your life. No matter how disgraceful or embarrassing it may be, you need to keep struggling to find your way out until the very end.” – Clare",
  "“There’s no point in running away from things that make you sad.” – Gintoki Sakata",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“People’s lives don’t end when they die. It ends when they lose faith.” – Itachi Uchiha",
  "“In this world, whenever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.” – Lelouch Lamperouge",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome Higurashi",
  "“A lesson without pain is meaningless, for you cannot gain something without sacrificing something else in return.” – Edward Elric",
  "“Even if I’m weak, I’ll keep fighting. Until the end, I’ll keep fighting.” – Allen Walker",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“I’ll take a potato chip… and eat it!” – Light Yagami",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I won’t run away anymore… I won’t go back on my word… that is my ninja way!” – Naruto Uzumaki",
  "“It’s not the face that makes someone a monster, it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“It’s not the power of the curse… it’s the power you give the curse.” – Naruto Uzumaki",
  "“When you have to save someone you love, it’s okay to feel weak.” – Erza Scarlet",
  "“I’m not gonna die in a place like this. The world is too big. I’m gonna continue my journey!” – Monkey D. Luffy",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“No matter how deep the night, it always turns to day, eventually.” – Brook",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rin Tohsaka",
  "“If you feel yourself hitting up against your limit, remember for what cause you clench your fists… remember why you started down this path, and let that memory carry you beyond your limit.” – Izuku Midoriya",
  "“I’m not a weapon of mass destruction; I’m a hero who’ll blast you!” – Katsuki Bakugo",
  "“Even if I’m weak, I’ll keep fighting. Until the end, I’ll keep fighting.” – Allen Walker",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“Don’t be so quick to throw away your life. No matter how disgraceful or embarrassing it may be, you need to keep struggling to find your way out until the very end.” – Clare",
  "“There’s no point in running away from things that make you sad.” – Gintoki Sakata",
  "“People’s lives don’t end when they die. It ends when they lose faith.” – Itachi Uchiha",
  "“In this world, whenever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.” – Lelouch Lamperouge",
  "“A lesson without pain is meaningless, for you cannot gain something without sacrificing something else in return.” – Edward Elric",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome Higurashi",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“I don’t want to be someone’s reason for unhappiness. I want to be a reason for someone’s happiness.” – Rokuro Enmado",
  "“People die if they are killed.” – Shirou Emiya",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“I’m the one who decides who I am!” – Rin Okumura",
  "“We’re all like fireworks. We climb, shine, and always go our separate ways and become further apart. But even if that time comes, let’s not disappear like a firework, and continue to shine forever.” – Hitsugaya Toushirou",
  "“We’re all like fireworks. We climb, shine, and always go our separate ways and become further apart. But even if that time comes, let’s not disappear like a firework, and continue to shine forever.” – Lelouch Lamperouge",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“I’m the one who decides who I am!” – Rin Okumura",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“I’m not a weapon of mass destruction; I’m a hero who’ll blast you!” – Katsuki Bakugo",
  "“People die if they are killed.” – Shirou Emiya",
  "“Don’t underestimate us. We don’t care about time or space or multitudes; we will tear you apart, and if we can’t find you, we’ll just erase you.” – Saitama",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rin Tohsaka",
  "“Even if I’m weak, I’ll keep fighting. Until the end, I’ll keep fighting.” – Allen Walker",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“We’re all like fireworks. We climb, shine, and always go our separate ways and become further apart. But even if that time comes, let’s not disappear like a firework, and continue to shine forever.” – Lelouch Lamperouge",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“People’s lives don’t end when they die. It ends when they lose faith.” – Itachi Uchiha",
  "“In this world, whenever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.” – Lelouch Lamperouge",
  "“A lesson without pain is meaningless, for you cannot gain something without sacrificing something else in return.” – Edward Elric",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome Higurashi",
  "“If you feel yourself hitting up against your limit, remember for what cause you clench your fists… remember why you started down this path, and let that memory carry you beyond your limit.” – Izuku Midoriya",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“No matter how deep the night, it always turns to day, eventually.” – Brook",
  "“When you have to save someone you love, it’s okay to feel weak.” – Erza Scarlet",
  "“I’m not gonna die in a place like this. The world is too big. I’m gonna continue my journey!” – Monkey D. Luffy",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“I’m the one who decides who I am!” – Rin Okumura",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“I want to live my life, not just exist.” – Shintarou Midorima",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“It’s not the face that makes someone a monster, it’s the choices they make with their lives.” – Naruto Uzumaki",
  "“The only thing we’re allowed to do is to believe that we won’t regret the choice we made.” – Levi Ackerman",
  "“In the end, we only regret the chances we didn’t take.” – Naruto Uzumaki",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“No matter how deep the night, it always turns to day, eventually.” – Brook",
  "“A lesson without pain is meaningless, for you cannot gain something without sacrificing something else in return.” – Edward Elric",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome Higurashi",
  "“Even in the darkest times, hope is something you can give yourself. The sky is always in the sky, and deep in the ocean, and the future will always be bright.” – Sanji",
  "“When you have to save someone you love, it’s okay to feel weak.” – Erza Scarlet",
  "“I’m not gonna die in a place like this. The world is too big. I’m gonna continue my journey!” – Monkey D. Luffy",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King!” – Monkey D. Luffy",
  "“People die if they are killed.” – Shirou Emiya",
  "“Even if I’m weak, I’ll keep fighting. Until the end, I’ll keep fighting.” – Allen Walker",
  "“The difference between the novice and the master is that the master has failed more times than the novice has tried.” – Koro-sensei",
  "“If you win, you live. If you lose, you die. If you don’t fight, you can’t win!” – Eren Yeager",
  "“We each need to find our own inspiration. Sometimes, it’s not easy.” – Kamina",
  "“The world is not beautiful; therefore, it is.” – Kino",
  "“In this world, whenever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.” – Lelouch Lamperouge",
  "“It’s okay not to be okay as long as you are not giving up.” – Karen Aijou",
  "“Being lonely is more painful than getting hurt.” – Monkey D. Luffy",
  "“Don’t underestimate us. We don’t care about time or space or multitudes; we will tear you apart, and if we can’t find you, we’ll just erase you.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“We’re all like fireworks. We climb, shine, and always go our separate ways and become further apart. But even if that time comes, let’s not disappear like a firework, and continue to shine forever.” – Lelouch Lamperouge",
  "“I’m the one who decides who I am!” – Rin Okumura",
  "“If you feel yourself hitting up against your limit, remember for what cause you clench your fists… remember why you started down this path, and let that memory carry you beyond your limit.” – Izuku Midoriya",
  "“It’s not the power of the curse… it’s the power you give the curse.” – Naruto Uzumaki",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!” – Naruto Uzumaki",
  "“The only way to truly escape the mundane is for you to constantly be evolving.” – Saitama",
  "“I may be empty, but I’m not worthless.” – Charlotte",
  "“I’m the one who decides who I am!” – Rin Okumura",
  "“Believe in yourself, and create your own destiny.” – Unknown",
  "“No matter how tough things get, don’t give up. Believe in yourself and push forward.” – Izuku Midoriya",
  "“A true hero isn’t measured by the size of their strength but by the strength of their heart.” – All Might",
  "“In the face of adversity, find your inner strength and overcome.” – Natsu Dragneel",
  "“The only way to achieve greatness is to first believe in yourself.” – Rokuro Enmado",
  "“You don’t have to be perfect to be amazing.” – Lucy Heartfilia",
  "“Our past doesn’t define us; it’s what we do in the present that shapes our future.” – Naruto Uzumaki",
  "“Don’t be afraid of failure; it’s a stepping stone to success.” – Edward Elric",
  "“Life is full of challenges, but every challenge is an opportunity for growth.” – Monkey D. Luffy",
  "“Be kind to yourself and others; it costs nothing but can mean everything.” – Nami",
  "“Sometimes, the smallest act of kindness can make the biggest impact.” – Sakura Haruno",
  "“It’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward.” – Rock Lee",
  "“The best way to predict the future is to create it.” – Lelouch Lamperouge",
  "“Dreams are meant to be pursued, no matter how impossible they seem.” – Yugi Mutou",
  "“The key to success is to never stop believing in your own potential.” – Erza Scarlet",
  "“The most important thing is to try and inspire people so that they can be great in whatever they want to do.” – Kobe Bryant",
  "“Don’t let fear hold you back from chasing your dreams.” – Sasuke Uchiha",
  "“Success is not final; failure is not fatal: It is the courage to continue that counts.” – Winston Churchill",
  "“Never forget the reason why you started in the first place.” – Ash Ketchum",
  "“Believe in your abilities, and you will be unstoppable.” – Ichigo Kurosaki",
  "“Your smile can brighten someone else’s day.” – Hinata Hyuga",
  "“You are never alone; your friends will always be by your side.” – Naruto Uzumaki",
  "“It’s okay to have weaknesses; they make us human.” – Rukia Kuchiki",
  "“Be true to yourself, and you’ll attract the right people into your life.” – Hinata Hyuga",
  "“You can achieve anything if you work hard and never give up.” – Natsu Dragneel",
  "“Even in the darkest times, there’s always a glimmer of hope.” – Erza Scarlet",
  "“When you have someone to protect, you become truly strong.” – Himura Kenshin",
  "“Don’t dwell on the past; focus on the present and the future.” – Yato",
  "“It’s not about how much time you have; it’s how you use it that counts.” – Nico Robin",
  "“Be the hero of your own story.” – Monkey D. Luffy",
  "“You are capable of more than you think; believe in your potential.” – Gon Freecss",
  "“Every day is a new beginning; seize it and make the most of it.” – Natsu Dragneel",
  "“Your smile can brighten someone else’s day.” – Hinata Hyuga",
  "“The future is not set in stone; you have the power to change it.” – Lelouch Lamperouge",
  "“Sometimes, the smallest acts of kindness can have the biggest impact.” – Yugi Mutou",
  "“Your true strength lies not in your power, but in your heart.” – Erza Scarlet",
  "“Don’t let the fear of falling keep you from flying.” – Sora",
  "“Believe in yourself, and others will believe in you too.” – Naruto Uzumaki",
  "“Embrace your uniqueness, for it is what makes you special.” – Rock Lee",
  "“No matter how dark the night, the sun will always rise.” – Kagome Higurashi",
  "“Your potential is limitless; don’t hold yourself back.” – Sakura Haruno",
  "“Every step you take brings you closer to your goal.” – Izuku Midoriya",
  "“Never forget the reason why you started in the first place.” – Ash Ketchum",
  "“Your smile can brighten someone else’s day.” – Hinata Hyuga",
  "“The only way to achieve greatness is to first believe in yourself.” – Rokuro Enmado",
  "“No matter how tough things get, don’t give up. Believe in yourself and push forward.” – Izuku Midoriya",
  "“A true hero isn’t measured by the size of their strength but by the strength of their heart.” – All Might",
  "“In the face of adversity, find your inner strength and overcome.” – Natsu Dragneel",
  "“The only way to achieve greatness is to first believe in yourself.” – Rokuro Enmado",
  "“You don’t have to be perfect to be amazing.” – Lucy Heartfilia",
  "“I’m not short! It’s just that I’m more down-to-earth than other people.” – Edward Elric",
  "“I’m not lazy; I’m just conserving energy.” – Houtarou Oreki",
  "“I’m going to be the Pirate King!” “You? A king? In your dreams!” “You’re right; I’m going to be the Pirate God!” – Monkey D. Luffy",
  "“I’m not a pervert; I’m just very appreciative of the female form.” – Master Roshi",
  "“I’m not a nerd; I’m just really good with computers.” – Konata Izumi",
  "“I don’t need a weapon. My friends are my power!” “And your friends need a weapon!” – Sora and Goofy",
  "“I’m not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.” – Lucy Heartfilia",
  "“I’m not stupid; I’m just too lazy to show how smart I am.” – Oreki Houtarou",
  "“I don’t snore; I dream I’m a motorcycle.” – Ichigo Kurosaki",
  "“I’m not fat; I’m just easy to see.” – Choji Akimichi",
  "“I don’t need a reason to help people.” – Zidane Tribal",
  "“I’m not arguing; I’m just explaining why I’m right.” – Itachi Uchiha",
  "“I don’t care about your opinion. I care about my pizza.” – Monkey D. Luffy",
  "“I’m not bossy. I just have better ideas.” – Erza Scarlet",
  "“I don’t need luck. I have firepower.” – Spike Spiegel",
  "“I’m not dumb; I’m just too lazy to show how smart I am.” – Shikamaru Nara",
  "“I don’t need a hug. I need coffee.” – Rin Tohsaka",
  "“I’m not antisocial; I’m just not user-friendly.” – Rei Kiriyama",
  "“I don’t have time to worry about how it happened. I’m too busy thinking about how to fix it.” – Roy Mustang",
  "“I’m not a man. I’m an eating machine!” – Goku",
  "“I don’t snore; I dream I’m a chainsaw.” – Luffy",
  "“I’m not a hero. I’m just a high school student with extraordinary powers.” – Izuku Midoriya",
  "“I don’t need a maid; I need a ninja.” – Saitama",
  "“I’m not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.” – Lucy Heartfilia",
  "“I don’t care about money. I just want to be fabulous.” – Juvia Lockser",
  "“I’m not addicted to ramen; I just really like it.” – Naruto Uzumaki",
  "“I’m not short; I’m fun-sized.” – Edward Elric",
  "“I don’t need to get a life. I’m a gamer; I have lots of lives.” – Keima Katsuragi",
  "“I’m not saying I’m Wonder Woman; I’m just saying no one has ever seen me and Wonder Woman in the same room together.” – Misaka Mikoto",
  "“I don’t care about age. I’m still young at heart… and slightly older in other places.” – Jiraiya",
  "“I’m not a pervert; I’m just misunderstood.” – Master Roshi",
  "“I don’t need a hug. I need coffee.” – Rin Tohsaka",
  "“I’m not lazy; I’m just energy-efficient.” – Oreki Houtarou",
  "“I don’t snore; I dream I’m a chainsaw.” – Luffy",
  "“I’m not a hero. I’m just a high school student with extraordinary powers.” – Izuku Midoriya",
  "“I don’t need a maid; I need a ninja.” – Saitama",
  "“I’m not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.” – Lucy Heartfilia",
  "“I don’t care about money. I just want to be fabulous.” – Juvia Lockser",
  "“I’m not addicted to ramen; I just really like it.” – Naruto Uzumaki",
  "“I’m not short; I’m fun-sized.” – Edward Elric",
  "“I don’t need to get a life. I’m a gamer; I have lots of lives.” – Keima Katsuragi",
  "“I’m not saying I’m Wonder Woman; I’m just saying no one has ever seen me and Wonder Woman in the same room together.” – Misaka Mikoto",
  "“I don’t care about age. I’m still young at heart… and slightly older in other places.” – Jiraiya",
  "“I’m not a pervert; I’m just misunderstood.” – Master Roshi",
  "“I don’t need a hug. I need coffee.” – Rin Tohsaka",
  "“I’m not lazy; I’m just energy-efficient.” – Oreki Houtarou",
  "“I don’t snore; I dream I’m a chainsaw.” – Luffy",
  "“I’m not a hero. I’m just a high school student with extraordinary powers.” – Izuku Midoriya",
  "“I don’t need a maid; I need a ninja.” – Saitama",
  "“I’m not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.” – Lucy Heartfilia",
  "“It’s not about the destination; it’s about the journey.” – Unknown",
  "“I’m not giving up, I’m just taking a break.” – Unknown",
  "“Even in the darkest times, there’s always a glimmer of hope.” – Unknown",
  "“The best way to predict the future is to create it.” – Unknown",
  "“Sometimes, the smallest act of kindness can have the biggest impact.” – Unknown",
  "“In the face of adversity, find your inner strength and overcome.” – Unknown",
  "“Believe in yourself, and others will believe in you too.” – Unknown",
  "“Life is full of challenges, but every challenge is an opportunity for growth.” – Unknown",
  "“Your true strength lies not in your power, but in your heart.” – Unknown",
  "“Don’t let the fear of falling keep you from flying.” – Unknown",
  "“Human strength lies in the ability to change yourself.” — Saitama, One Punch Man",
  "“You can die anytime, but living takes true courage.” — Kenshin Himura, Rurouni Kenshin",
  "“Fear is not evil. It tells you what weakness is. And once you know your weakness, you can become stronger as well as kinder.” — Gildarts Clive, Fairy Tail",
  "“A person can change, at the moment when the person wishes to change.” — Haruhi Fujioka, Ouran Highschool Host Club",
  "“You will never be able to love anybody else until you love yourself.” — Lelouch Lamperouge, Code Geass",
  "“All we can do is live until the day we die. Control what we can…and fly free.” — Deneil Young, Space Brothers",
  "“If you don’t take risks, you can’t create a future.” — Monkey D. Luffy, One Piece",
  "“If you don’t share someone’s pain, you can never understand them.” — Nagato, Naruto",
  "“There’s no shame in falling down! True shame is to not stand up again!” — Shintaro Midorima, Kuroko’s Basketball",
  "“When you hit the point of no return, that’s the moment it truly becomes a journey. If you can still turn back, it’s not really a journey.” — Hinata Miyake, A Place Further than the Universe",
  "“The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.” — Roy Mustang, Full Metal Alchemist",
  "“Simplicity is the easiest path to true beauty.” — Seishuu Handa, Barakamon",
  "“The past is the past. We cannot indulge ourselves in memories and destroy the present.” — Murata Ken, Kyou Kara Maou!",
  "“Knowing what it feels like to be in pain is exactly why we try to be kind to others.” — Jiraiya, Naruto",
  "Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.” — Mavis Vermillon, Fairy Tail",
  "“All things change in a dynamic environment. Your effort to remain what you are is what limits you.” — Puppet Master, Ghost in the Shell",
  "“No matter how many weapons you have, no matter how great your technology might be, the world cannot live without love.” — Sheeta, Castle in the Sky",
  "“A heart’s a heavy burden.” — Sophie, Howl’s Moving Castle",
  "“The scars you can’t see are the hardest to heal.” — Nao Tomori, Charlotte",
  "“It’s not dying that frightens us. It’s living without ever having done our best.” — The Elder, Castlevania",
  "“No matter how messed up things get, you can always figure out the best solution.” —Eren Yeager, Attack on Titan",
  "“There’s no future for people who worship the future…” — Shun Kazama, From Up on Poppy Hill",
  "“Searching for someone to blame is such a pain.” — Satoru Goju, Jujutsu Kaisen",
  "“Sometimes, we have to look beyond what we want and do what’s best.” — Piccolo, Dragon Ball Z",
  "“It’s quiet, but can you hear it? Little by little, the tides are changing, and the world with them.” — Shakuyaku, One Piece",
  "“Believe in your own power.” — Mikasa Ackerman, Attack on Titan",
  "“Helping other people is the best way to make up for your mistakes.” — Kenshin Himura, Rurouni Kenshin",
  "“Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable; we have to face them. It’s what being human is all about.” — Jet Black, Cowboy Bebop",
  "“Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully.” — Koro-sensei, Assassination Classroom",
  "“Like I always say, can’t find a door? Make your own.” — Edward Elric, Fullmetal Alchemist",
  "“People who continue to put their lives on the line to defend their faith become heroes and continue to exist on in legend.” — Naruto Uzumaki, Naruto",
  "“We need to stop living for others. From now on…Let’s live for ourselves!” — Historia Reiss, Attack on Titan",
  "“As the living, it is our responsibility to carry out the wishes of the ones who are gone.” — Akame, Akame Ga Kill",
  "“Those who stand at the top determine what’s wrong and what’s right! This very place is neutral ground! Justice will prevail, you say? But, of course, it will! Whoever wins this war becomes justice!” — Donquixote Doflamingo, One Piece",
  "“Forgetting is like a wound. The wound may heal, but it has already left a scar.” — Monkey D. Luffy, One Piece",
  "“You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face.” — Roronoa Zoro, One Piece",
  "“People who can’t throw something important away can never hope to change anything.” — Armin Arlert, Attack on Titan",
  "“If you begin to regret, you’ll dull your future decisions and let others make your choices for you. All that’s left for you then is to die. Nobody can foretell the outcome. Each decision you make holds meaning only by affecting your next decision.” — Erwin Smith, Attack on Titan",
  "Fools who don’t respect the past are likely to repeat it.” — Nico Robin, One Piece",
  "“A life that lives without doing anything is the same as a slow death.” — Lelouch, Code Geass: Lelouch of the Rebellion",
  "“The strong should aid and protect the weak. Then, the weak will become strong, and they, in turn, will aid and protect those weaker than them. That is the law of nature.” — Tanjiro Kamado, Demon Slayer",
  "“I guess, as long as I have life, all I can do is fight with all my might.” — Subaru Natsuki, Re:Zero",
  "“When you give up, that’s when the game ends.” — Mitsuyoshi Anzai, Slam Dunk",
  "“You’re gonna care what other people think and be someone you’re not your whole life? You’re fine as you are. So, talk in your own words.” — Ymir, Attack on Titan",
  "“What good are dreams if all you do is work? There’s more to life than hitting the books, you know.” — Tamaki Suoh, Ouran High School Host Club",
  "“I see now that the circumstances of one’s birth are irrelevant. It is what you do with the gift of life that determines who you are.” — Mewtwo, Pokemon: The First Movie",
  "“Life is short, so it will be appreciated. We live to our fullest due to that.” — Heiji Hattori, Detective Conan",
  "“If you never listen to anyone, you can’t give proper advice.” — Monk Momoaki, The Boy and the Beast",
  "“The important thing is not how long you live. It’s what you accomplish with your life.” — Grovyle, Pokemon",
  "“Push through the pain. Giving up hurts more.” — Vegeta, Dragon Ball Z",
  "“When a man learns to love, he must bear the risk of hatred.” — Madara Uchiha, Naruto",
  "“When you fall in love with someone, you start wanting to know lots of things about that person.” — Ninako Kinoshita, Strobe Edge",
  "Even if I lose this feeling, I’m sure I’ll just fall in love with you all over again. — Syaoran Li, Cardcaptor Sakura",
  "“Even if I searched the world over, no one could compare to you.” — Hikaru Hitachiin, Ouran Highschool Host Club",
  "“Love is simply an electrical bug in the human neural circuit.” — Akasaka Ryuunosuke, My Pet Girl Sakurasou",
  "“However little strength I’m capable of, I’ll do everything humanly possible to protect the people I love.” — Roy Mustang, Fullmetal Alchemist",
  "“Love is like a mirror that reflects your bad side. Especially when it’s unrequited, you get envious, jealous, prejudiced and resentful. You have to face all sorts of emotions, but there’s no reason to find that shameful.” — Margery Daw, Shakugan No Shana",
  "“Once you fall in love, you really love that person through thick and thin.” — Oka Chinami, Golden Time!",
  "“If it’s possible for one person to be hurt by another, then it’s possible for that person to be healed by another.” — Sohma Hatori, Fruits Basket",
  "“Even if I lose this feeling, I’m sure that I’ll just fall in love with you all over again.” –Syaoran Li, Cardcaptor Sakura",
  "“When it comes to people you really love, you don’t care about yourself.” — Kurosawa Yamato, Say I Love You",
  "“The moment you find the courage to give up your life for someone…would be the moment you understand love.” — Kenshin Himura, Samurai X",
  "“I love you with all my heart…If you were to stay here with me, there would be no regrets…because every day we’d do something fun, we’d be happy, I swear…I would do anything for you! So…please, just stay with me!” — Sakura Haruno, Naruto",
  "“You changed me! Your smile is what saved me! That is why I’m not afraid to die protecting you! Because I love you.” — Hyuuga Hinata, Naruto",
  "“Human strength lies in the ability to change yourself.” — Saitama, One Punch Man",
  "“You can die anytime, but living takes true courage.” — Kenshin Himura, Rurouni Kenshin",
  "“Fear is not evil. It tells you what weakness is. And once you know your weakness, you can become stronger as well as kinder.” — Gildarts Clive, Fairy Tail",
  "“A person can change, at the moment when the person wishes to change.” — Haruhi Fujioka, Ouran Highschool Host Club",
  "“You will never be able to love anybody else until you love yourself.” — Lelouch Lamperouge, Code Geass",
  "“All we can do is live until the day we die. Control what we can…and fly free.” — Deneil Young, Space Brothers",
  "“If you don’t take risks, you can’t create a future.” — Monkey D. Luffy, One Piece",
  "“If you don’t share someone’s pain, you can never understand them.” — Nagato, Naruto",
  "“There’s no shame in falling down! True shame is to not stand up again!” — Shintaro Midorima, Kuroko’s Basketball",
  "“When you hit the point of no return, that’s the moment it truly becomes a journey. If you can still turn back, it’s not really a journey.” — Hinata Miyake, A Place Further than the Universe",
  "“The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.” — Roy Mustang, Full Metal Alchemist",
  "“Simplicity is the easiest path to true beauty.” — Seishuu Handa, Barakamon",
  "“The past is the past. We cannot indulge ourselves in memories and destroy the present.” — Murata Ken, Kyou Kara Maou!",
  "“Knowing what it feels like to be in pain is exactly why we try to be kind to others.” — Jiraiya, Naruto",
  "Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.” — Mavis Vermillon, Fairy Tail",
  "“All things change in a dynamic environment. Your effort to remain what you are is what limits you.” — Puppet Master, Ghost in the Shell",
  "“No matter how many weapons you have, no matter how great your technology might be, the world cannot live without love.” — Sheeta, Castle in the Sky",
  "“A heart’s a heavy burden.” — Sophie, Howl’s Moving Castle",
  "“The scars you can’t see are the hardest to heal.” — Nao Tomori, Charlotte",
  "“It’s not dying that frightens us. It’s living without ever having done our best.” — The Elder, Castlevania",
  "“No matter how messed up things get, you can always figure out the best solution.” —Eren Yeager, Attack on Titan",
  "“There’s no future for people who worship the future…” — Shun Kazama, From Up on Poppy Hill",
  "“Searching for someone to blame is such a pain.” — Satoru Goju, Jujutsu Kaisen",
  "“Sometimes, we have to look beyond what we want and do what’s best.” — Piccolo, Dragon Ball Z",
  "“It’s quiet, but can you hear it? Little by little, the tides are changing, and the world with them.” — Shakuyaku, One Piece",
  "“Believe in your own power.” — Mikasa Ackerman, Attack on Titan",
  "“Helping other people is the best way to make up for your mistakes.” — Kenshin Himura, Rurouni Kenshin",
  "“Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable; we have to face them. It’s what being human is all about.” — Jet Black, Cowboy Bebop",
  "“Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully.” — Koro-sensei, Assassination Classroom",
  "“Like I always say, can’t find a door? Make your own.” — Edward Elric, Fullmetal Alchemist",
  "“People who continue to put their lives on the line to defend their faith become heroes and continue to exist on in legend.” — Naruto Uzumaki, Naruto",
  "“We need to stop living for others. From now on…Let’s live for ourselves!” — Historia Reiss, Attack on Titan",
  "“As the living, it is our responsibility to carry out the wishes of the ones who are gone.” — Akame, Akame Ga Kill",
  "“Those who stand at the top determine what’s wrong and what’s right! This very place is neutral ground! Justice will prevail, you say? But, of course, it will! Whoever wins this war becomes justice!” — Donquixote Doflamingo, One Piece",
  "“Forgetting is like a wound. The wound may heal, but it has already left a scar.” — Monkey D. Luffy, One Piece",
  "“You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face.” — Roronoa Zoro, One Piece",
  "“People who can’t throw something important away can never hope to change anything.” — Armin Arlert, Attack on Titan",
  "“If you begin to regret, you’ll dull your future decisions and let others make your choices for you. All that’s left for you then is to die. Nobody can foretell the outcome. Each decision you make holds meaning only by affecting your next decision.” — Erwin Smith, Attack on Titan",
  "Fools who don’t respect the past are likely to repeat it.” — Nico Robin, One Piece",
  "“A life that lives without doing anything is the same as a slow death.” — Lelouch, Code Geass: Lelouch of the Rebellion",
  "“The strong should aid and protect the weak. Then, the weak will become strong, and they, in turn, will aid and protect those weaker than them. That is the law of nature.” — Tanjiro Kamado, Demon Slayer",
  "“I guess, as long as I have life, all I can do is fight with all my might.” — Subaru Natsuki, Re:Zero",
  "“When you give up, that’s when the game ends.” — Mitsuyoshi Anzai, Slam Dunk",
  "“You’re gonna care what other people think and be someone you’re not your whole life? You’re fine as you are. So, talk in your own words.” — Ymir, Attack on Titan",
  "“What good are dreams if all you do is work? There’s more to life than hitting the books, you know.” — Tamaki Suoh, Ouran High School Host Club",
  "“I see now that the circumstances of one’s birth are irrelevant. It is what you do with the gift of life that determines who you are.” — Mewtwo, Pokemon: The First Movie",
  "“Life is short, so it will be appreciated. We live to our fullest due to that.” — Heiji Hattori, Detective Conan",
  "“If you never listen to anyone, you can’t give proper advice.” — Monk Momoaki, The Boy and the Beast",
  "“The important thing is not how long you live. It’s what you accomplish with your life.” — Grovyle, Pokemon",
  "“Push through the pain. Giving up hurts more.” — Vegeta, Dragon Ball Z",
  "“When a man learns to love, he must bear the risk of hatred.” — Madara Uchiha, Naruto",
  "“When you fall in love with someone, you start wanting to know lots of things about that person.” — Ninako Kinoshita, Strobe Edge",
  "Even if I lose this feeling, I’m sure I’ll just fall in love with you all over again. — Syaoran Li, Cardcaptor Sakura",
  "“Even if I searched the world over, no one could compare to you.” — Hikaru Hitachiin, Ouran Highschool Host Club",
  "“Love is simply an electrical bug in the human neural circuit.” — Akasaka Ryuunosuke, My Pet Girl Sakurasou",
  "“However little strength I’m capable of, I’ll do everything humanly possible to protect the people I love.” — Roy Mustang, Fullmetal Alchemist",
  "“Love is like a mirror that reflects your bad side. Especially when it’s unrequited, you get envious, jealous, prejudiced and resentful. You have to face all sorts of emotions, but there’s no reason to find that shameful.” — Margery Daw, Shakugan No Shana",
  "“Once you fall in love, you really love that person through thick and thin.” — Oka Chinami, Golden Time!",
  "“If it’s possible for one person to be hurt by another, then it’s possible for that person to be healed by another.” — Sohma Hatori, Fruits Basket",
  "“Even if I lose this feeling, I’m sure that I’ll just fall in love with you all over again.” –Syaoran Li, Cardcaptor Sakura",
  "“When it comes to people you really love, you don’t care about yourself.” — Kurosawa Yamato, Say I Love You",
  "“The moment you find the courage to give up your life for someone…would be the moment you understand love.” — Kenshin Himura, Samurai X",
  "“I love you with all my heart…If you were to stay here with me, there would be no regrets…because every day we’d do something fun, we’d be happy, I swear…I would do anything for you! So…please, just stay with me!” — Sakura Haruno, Naruto",
  "“You changed me! Your smile is what saved me! That is why I’m not afraid to die protecting you! Because I love you.” — Hyuuga Hinata, Naruto",
  "“Love is never as simple as sharing the same path.” — Khamsin, Shakugan No Shana",
  "“A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.” – Fullmetal Alchemist",
  "“The world isn’t perfect. But it’s there for us, doing the best it can…that’s what makes it so damn beautiful.” – Roy Mustang, Fullmetal Alchemist",
  "“The moment you think of giving up, think of the reason why you held on so long.” – Natsu Dragneel, Fairy Tail",
  "“If you don’t take risks, you can’t create a future.” – Monkey D. Luffy, One Piece",
  "“You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.” – Ging Freecss, Hunter x Hunter",
  "“To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.” – Matsumoto Rangiku, Bleach",
  "“A real ninja is one who endures no matter what gets thrown at him. All you do need is the guts to never give up.” – Jiraiya, Naruto",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku, Dragon Ball Z",
  "“Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.” – Kenshin Himura, Rurouni Kenshin",
  "“Hard work is worthless for those that don’t believe in themselves.” – Naruto Uzumaki, Naruto",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki, Naruto",
  "“When you give up, that’s when the game is over.” – Mitsuyoshi Anzai, Slam Dunk",
  "“If you can’t do something, then don’t. Focus on what you can do.” – Shiroe, Log Horizon",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rintarou Okabe, Steins;Gate",
  "“The world is not beautiful, therefore it is.” – Kino, Kino’s Journey",
  "“I’ll take a potato chip…and eat it!” – Light Yagami, Death Note",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki, Naruto",
  "“People’s lives don’t end when they die, it ends when they lose faith.” – Itachi Uchiha, Naruto",
  "“To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.” – Matsumoto Rangiku, Bleach",
  "“Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.” – Kenshin Himura, Rurouni Kenshin",
  "“A real ninja is one who endures no matter what gets thrown at him. All you do need is the guts to never give up.” – Jiraiya, Naruto",
  "“The world isn’t perfect. But it’s there for us, doing the best it can…that’s what makes it so damn beautiful.” – Roy Mustang, Fullmetal Alchemist",
  "“If you don’t take risks, you can’t create a future.” – Monkey D. Luffy, One Piece",
  "“I am not a king, I am not a god, I am… worse!” – Madara Uchiha, Naruto",
  "“Bang!” – Spike Spiegel, Cowboy Bebop",
  "“It’s just pathetic to give up on something before you even give it a shot.” – Reiko Mikami, Another",
  "“Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.” – Gildarts Clive, Fairy Tail",
  "“If you can’t do something, then don’t. Focus on what you can do.” – Shiroe, Log Horizon",
  "“To defeat evil, I shall become an even greater evil.” – Lelouch Lamperouge, Code Geass",
  "“I want to be a healer, and love all humans.” – Inuyasha, Inuyasha",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki, Naruto",
  "“People’s lives don’t end when they die, it ends when they lose faith.” – Itachi Uchiha, Naruto",
  "“You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.” – Ging Freecss, Hunter x Hunter",
  "“We are all like fireworks. We climb, we shine and always go our separate ways and become further apart. But even if that time comes, let’s not disappear like a firework, and continue to shine… forever.” – Hitsugaya Toshiro, Bleach",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku, Dragon Ball Z",
  "“The world is not beautiful, therefore it is.” – Kino, Kino’s Journey",
  "“No one knows what the future holds. That’s why its potential is infinite.” – Rintarou Okabe, Steins;Gate",
  "“The moment you think of giving up, think of the reason why you held on so long.” – Natsu Dragneel, Fairy Tail",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki, Naruto",
  "“You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face.” – Roronoa Zoro, One Piece",
  "“I do not need a reason to save someone.” – Asta, Black Clover",
  "“To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.” – Matsumoto Rangiku, Bleach",
  "“A lesson without pain is meaningless. That’s because no one can gain without sacrificing something.” – Fullmetal Alchemist",
  "“It’s not about how many times you fall, but how many times you get back up.” – Hinata Shoyo, Haikyuu!!",
  "“If you don’t share someone’s pain, you can never understand them.” – Nagato, Naruto Shippuden",
  "“Even if I lose this feeling, I’m sure that I’ll just fall in love with you all over again.” – Syaoran Li, Cardcaptor Sakura",
  "“I won’t hate that person. Even if it kills me. Because if I do, it means that person won.” – Makoto Naegi, Danganronpa",
  "“No matter how much you change, please don’t forget how it felt when we were together.” – Hinata Hideki, Angel Beats!",
  "“It’s not like I wanted to like you. I just started to, and now I can’t stop.” – Sawako Kuronuma, Kimi ni Todoke",
  "“Loving someone means being prepared to take the good and the bad.” – Kaori Miyazono, Your Lie in April",
  "“Love is never as simple as sharing the same path.” – Khamsin, Shakugan no Shana",
  "“No matter what kind of past you had, you are not alone anymore. I’ll protect you.” – Yuuki Asuna, Sword Art Online",
  "“I don’t want to lose you again.” – Yui, Angel Beats!",
  "“Love is like a mirror that reflects your bad side. Especially when it’s unrequited.” – Ritsu Kawai, Loveless",
  "“I’ll make you so in love with me, that every time our lips touch, you’ll die a little inside.” – Ai Yazawa, Nana",
  "“I am the bone of my sword, Steel is my body and fire is my blood.” – Archer, Fate/Stay Night",
  "“The moment you find the courage to give up your life for someone… would be the moment you understand love.” – Kenshin Himura, Rurouni Kenshin",
  "“The scariest thing about distance is you don’t know whether they’ll miss you or forget about you.” – Kurosaki Ichigo, Bleach",
  "“I’ll always be there for you, even if you don’t see me.” – Takashi Natsume, Natsume’s Book of Friends",
  "“Love and death are two uninvited guests. Nobody knows when they come, but both do the same work; one takes the heart and the other takes its beat.” – Hitsugaya Toshiro, Bleach",
  "“It’s not the face that makes someone a monster; it’s the choices they make with their lives.” – Naruto Uzumaki, Naruto",
  "“Even though I told myself I wouldn’t cry, I couldn’t stop the tears from falling.” – Takashi Natsume, Natsume’s Book of Friends",
  "“I want to go somewhere… Far away. Somewhere I won’t feel anything… anymore.” – Rukia Kuchiki, Bleach",
  "“I always have to cry myself to sleep, telling myself that I am the person who will not be loved by anyone.” – Subaru Natsuki, Re: Zero",
  "“Why does no one believe me when I say I’m lonely?” – Tomoko Kuroki, WataMote",
  "“I wonder if I could have been a different person, living a different life.” – Inuyasha, Inuyasha",
  "“I don’t want anyone to see me cry… I don’t want anyone to hear me cry.” – Hatori Sohma, Fruits Basket",
  "“I’m not alone. I have my friends with me. But… why do I still feel this way?” – Taichi Yagami, Digimon",
  "“Sometimes I feel like I’m fated to never be happy.” – Kouta Kazuraba, Kamen Rider Gaim",
  "“There are times when I think about dying. I feel as if my life is empty. I hate myself.” – Nana Osaki, Nana",
  "“The thing I was looking for wasn’t anywhere in the world. It was inside of me, all along.” – Ayumu Aikawa, Is This a Zombie?",
  "“Even if you could say I’ll never be lonely, I can’t be happy now. There is no place where I belong.” – Kyo Sohma, Fruits Basket",
  "“I’m so tired of living.” – Yuki Nagato, The Melancholy of Haruhi Suzumiya",
  "“I’m afraid to know the truth. I’m afraid to love someone again.” – Haruhi Fujioka, Ouran High School Host Club",
  "“It’s better to be hurt than to hurt others. Nice people can be happy with just that.” – Kanade Tachibana, Angel Beats!",
  "\"Power comes in response to a need, not a desire.\" – Goku, Dragon Ball Z",
  "\"The world isn’t perfect. But it’s there for us, doing the best it can… That’s what makes it so damn beautiful.\" – Roy Mustang, Fullmetal Alchemist: Brotherhood",
  "\"In the world, the strong devour the weak. Who is the strong? I am!\" – Alucard, Hellsing",
  "\"I’ll take a potato chip… and eat it!\" – Light Yagami, Death Note",
  "\"People die when they are killed.\" – Shirou Emiya, Fate/Stay Night",
  "\"To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.\" – Matsumoto Rangiku, Bleach",
  "\"Whatever you lose, you’ll find it again. But what you throw away, you’ll never get back.\" – Himura Kenshin, Rurouni Kenshin",
  "\"We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today!\" – Natsu Dragneel, Fairy Tail",
  "\"It’s not the face that makes someone a monster; it’s the choices they make with their lives.\" – Naruto Uzumaki, Naruto",
  "\"If you don’t take risks, you can’t create a future!\" – Monkey D. Luffy, One Piece",
  "\"You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.\" – Ging Freecss, Hunter x Hunter",
  "\"Sometimes, I do feel like I’m a failure. Like there’s no hope for me. But even so, I’m not going to give up.\" – Izuku Midoriya, My Hero Academia",
  "\"I am not a hero because I want your approval. I do it because I want to!\" – Saitama, One Punch Man",
  "\"The past makes you wanna die out of regret, and the future makes you depressed out of anxiety. So by elimination, the present is likely the happiest time.\" – Hachiman Hikigaya, Oregairu",
  "\"Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.\" – Gildarts Clive, Fairy Tail",
  "\"A lesson without pain is meaningless. That’s because you cannot gain something without sacrificing something else in return.\" – Edward Elric, Fullmetal Alchemist: Brotherhood",
  "\"The only ones who should kill are those prepared to be killed.\" – Lelouch Lamperouge, Code Geass",
  "\"Forgetting is like a wound. The wound may heal, but it has already left a scar.\" – Monkey D. Luffy, One Piece",
  "\"If you don’t share someone’s pain, you can never understand them.\" – Nagato (Pain), Naruto Shippuden",
  "\"If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!\" – Naruto Uzumaki, Naruto",
  "\"A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.\" – Jiraiya, Naruto",
  "\"When you give up, that’s when the game is over.\" – Mitsuyoshi Anzai, Slam Dunk",
  "\"No matter how deep the night, it always turns to day, eventually.\" – Brook, One Piece",
  "\"Hard work is worthless for those that don’t believe in themselves.\" – Naruto Uzumaki, Naruto",
  "\"It’s not the future I dream of anymore, only the past.\" – Armin Arlert, Attack on Titan",
  "\"Don’t give up! There’s no shame in falling down! True shame is to not stand up again!\" – Shintaro Midorima, Kuroko no Basket",
  "\"The moment you think of giving up, think of the reason why you held on so long.\" – Natsu Dragneel, Fairy Tail",
  "\"We are all like fireworks: We climb, we shine, and always go our separate ways and become further apart. But even when that time comes, let’s not disappear like a firework, and continue to shine… forever.\" – Hitsugaya Toushirou, Bleach",
  "\"A dropout will beat a genius through hard work.\" – Rock Lee, Naruto",
  "\"I won’t run away anymore… I won’t go back on my word… that is my ninja way!\" – Naruto Uzumaki, Naruto",
  "\"We should live our lives to the fullest. You never know, we might be dead by tomorrow.\" – Kaori Miyazono, Your Lie in April",
  "\"If you can’t do something, then don’t. Focus on what you can do.\" – Shiroe, Log Horizon",
  "\"The world’s not perfect, but it’s there for us trying the best it can. That’s what makes it so damn beautiful.\" – Roy Mustang, Fullmetal Alchemist: Brotherhood",
  "\"If you don’t take risks, you can’t create a future!\" – Monkey D. Luffy, One Piece",
  "\"If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be!\" – Naruto Uzumaki, Naruto",
  "\"You can’t sit around envying other people’s worlds. You have to go out and change your own.\" – Shinichi Chiaki, Nodame Cantabile",
  "\"Whatever you do, enjoy it to the fullest. That is the secret of life.\" – Rider, Fate/Zero",
  "\"I do not fear death. I fear only that my rage will fade over time.\" – Kurapika, Hunter x Hunter",
  "\"Don’t forget to love yourself.\" – Natsu Dragneel, Fairy Tail",
  "\"There’s no need to rush. No need to sparkle. No need to be anybody but oneself.\" – Jibanyan, Yo-kai Watch",
  "\"The world is cruel, but it’s also very beautiful.\" – Mikasa Ackerman, Attack on Titan",
  "\"Even if no one believes in you, stick out your best and scream your defiance!\" – Rintarou Okabe, Steins;Gate",
  "\"Whatever you lose, you’ll find it again. But what you throw away, you’ll never get back.\" – Himura Kenshin, Rurouni Kenshin",
  "\"Sometimes, you have to take a leap of faith first. The trust part comes later.\" – Yui Hirasawa, K-On!",
  "\"The moment you think of giving up, think of the reason why you held on so long.\" – Natsu Dragneel, Fairy Tail",
  "\"It’s not the face that makes someone a monster; it’s the choices they make with their lives.\" – Naruto Uzumaki, Naruto",
  "\"The only thing we’re allowed to do is to believe that we won’t regret the choice we made.\" – Levi Ackerman, Attack on Titan",
  "\"If you really want to be strong… Stop caring about what your surrounding thinks of you!\" – Saitama, One Punch Man",
  "\"If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.\" – Naruto Uzumaki, Naruto",
  "\"You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.\" – Ging Freecss, Hunter x Hunter",
  "\"Forgetting is like a wound. The wound may heal, but it has already left a scar.\" – Monkey D. Luffy, One Piece",
  "\"The past makes you wanna die out of regret, and the future makes you depressed out of anxiety. So by elimination, the present is likely the happiest time.\" – Hachiman Hikigaya, Oregairu",
  "\"Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.\" – Gildarts Clive, Fairy Tail",
  "\"People, who can’t throw something important away, can never hope to change anything.\" – Armin Arlert, Attack on Titan",
  "\"The world’s not perfect, but it’s there for us, doing the best it can. That’s what makes it so damn beautiful.\" – Roy Mustang, Fullmetal Alchemist: Brotherhood",
  "\"A lesson without pain is meaningless. That’s because you cannot gain something without sacrificing something else in return.\" – Edward Elric, Fullmetal Alchemist: Brotherhood",
  "\"Life is not a game of luck. If you wanna win, work hard.\" – Sora, No Game No Life",
  "\"No matter how deep the night, it always turns to day, eventually.\" – Brook, One Piece",
  "\"Living is painful. It’s painful, but we can’t let it stop us.\" – Ciel Phantomhive, Black Butler",
  "\"We are all like fireworks: We climb, we shine, and always go our separate ways and become further apart. But even when that time comes, let’s not disappear like a firework, and continue to shine… forever.\" – Hitsugaya Toushirou, Bleach",
  "\"Even if I lose this feeling, I’m sure I’ll just fall in love with you all over again.\" – Syaoran Li, Cardcaptor Sakura",
  "\"No matter how much time passes, being with you doesn’t feel like time at all.\" – Takashi Natsume, Natsume’s Book of Friends",
  "\"Love is like a mirror. When you love another you become his mirror and he becomes yours. And reflecting each other’s love you see infinity.\" – Lelouch Lamperouge, Code Geass",
  "\"I love you not only for what you are, but for what I am when I am with you.\" – Roy Mustang, Fullmetal Alchemist",
  "\"It was like you brought color to my life. You changed my life, all by yourself.\" – Sawako Kuronuma, Kimi ni Todoke",
  "\"Being in love with someone is a wonderful thing, isn’t it? You always want to be with them. You always want to touch them.\" – Takeo Gouda, My Love Story!!",
  "\"I won’t let anyone stand in the way of my love for you.\" – Inuyasha, Inuyasha",
  "\"I wanted to be with you. Even if we couldn't do anything, I wanted to be with you.\" – Himura Kenshin, Rurouni Kenshin",
  "\"When you’re in love, you want to become that person’s everything. You want to be their reason to live.\" – Syaoran Li, Cardcaptor Sakura",
  "\"The moment you find the courage to give up your life for someone would be the moment you understand love.\" – Kenshin Himura, Rurouni Kenshin",
  "\"You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.\" – Ging Freecss, Hunter x Hunter",
  "\"I’ve always been afraid of losing the people I love. But sometimes I wonder, is there anyone out there afraid to lose me?\" – Natsu Dragneel, Fairy Tail",
  "\"No matter how much I want you, I can't have you. And that hurts more than anything else.\" – Kaoru Kamiya, Rurouni Kenshin",
  "\"Even if it’s a lie, I’m glad to have you by my side.\" – Kaori Miyazono, Your Lie in April",
  "\"You were always there for me, and that’s all I needed.\" – Sakura Haruno, Naruto Shippuden",
  "\"You once told me you were a bird who was trapped in a cage. I understand it now. Your cage is something that can’t be seen with the naked eye, but still it imprisons you.\" – Inuyasha, Inuyasha",
  "\"When you fall in love with someone, you start wanting to know everything about them.\" – Masamune Izumi, Eromanga Sensei",
  "\"Even if things are painful and tough, people should appreciate what it means to be alive.\" – Yato, Noragami",
  "\"Love is simply something you can’t put into words.\" – Kagome Higurashi, Inuyasha",
  "\"Love is the reason why people are brought together and also torn apart.\" – Holo, Spice and Wolf",
  "\"It’s not the face that makes someone a monster; it’s the choices they make with their lives.\" – Naruto Uzumaki, Naruto",
  "\"Why should I apologize for being a monster? Has anyone ever apologized for turning me into one?\" – Juuzou Suzuya, Tokyo Ghoul",
  "\"I don’t want to run away anymore. I want to face my life, and make the right choices.\" – Makoto Naegi, Danganronpa: The Animation",
  "\"I bet dead people are easier to get along with.\" – Crona, Soul Eater",
  "\"Perhaps the companionship of an evil person is preferable to loneliness.\" – Gaara, Naruto",
  "\"The two of us aren’t so different. My whole life I’ve desired from others. I felt bitter to them, wanted to hurt them, and longed for them to disappear.\" – Tomura Shigaraki, My Hero Academia",
  "\"The loneliest people are the kindest, the saddest people smile the brightest, and the most damaged people are the wisest. All because they do not wish to see anyone else suffer the way they do.\" – Jellal Fernandes, Fairy Tail",
  "\"I always wanted to be loved. I just wanted to be loved.\" – Gaara, Naruto",
  "\"You said you love me, but that was a lie. You only loved yourself.\" – Kaworu Nagisa, Neon Genesis Evangelion",
  "\"There’s no way we could meet. But one thing is certain. If we see each other, we’ll know. That you were the one who was inside my heart.\" – Makoto Shinkai, 5 Centimeters Per Second",
  "\"There are no regrets. If one can be proud of one’s life, one should not wish for another chance.\" – Saber, Fate/Stay Night",
  "\"It was never about anyone else, it was all about me wanting to feel normal.\" – Touka Kirishima, Tokyo Ghoul",
  "\"I wish people who have wronged me, all the pain and suffering they caused.\" – Juuzou Suzuya, Tokyo Ghoul",
  "\"I wish people could be more understanding. I wish they knew how hard it is to be left alone.\" – Shinji Ikari, Neon Genesis Evangelion",
  "\"It’s only natural. I mean, all things that have a shape will eventually break. Why would you be any different?\" – Yoko Littner, Gurren Lagann",
  "\"I’m not used to hearing kind words… they make me kind of happy.\" – Nezuko Kamado, Demon Slayer",
  "\"The scariest thing about killing people is getting used to it.\" – Ken Kaneki, Tokyo Ghoul",
  "\"When you lose something, you understand its value.\" – Saitama, One Punch Man",
  "\"Even in the midst of our laughter, I am filled with an empty sadness.\" – Kaoru Miyazono, Your Lie in April",
  "\"The worst part of being strong is that no one ever asks if you’re okay.\" – Mikasa Ackerman, Attack on Titan",
  "“People’s lives don’t end when they die, it ends when they lose faith.” – Itachi Uchiha (Naruto)",
  "“If you don’t take risks, you can’t create a future!” – Monkey D. Luffy (One Piece)",
  "“If you don’t like your destiny, don’t accept it.” – Naruto Uzumaki (Naruto)",
  "“If you don’t share someone’s pain, you can never understand them.” – Nagato (Naruto)",
  "“Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.“ – Himura Kenshin (Rurouni Kenshin)",
  "“We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today!” – Natsu Dragneel (Fairy Tail)",
  "“Why should I apologize for being a monster? Has anyone ever apologized for turning me into one?” – Juuzou Suzuya (Tokyo Ghoul)",
  "“People become stronger because they have memories they can’t forget.” – Tsunade (Naruto)",
  "“I’ll leave tomorrow’s problems to tomorrow’s me.” – Saitama (One-Punch Man)",
  "“Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable, we have to face them. It’s what being human is all about.” – Jet Black (Cowboy Bebop)",
  "“Anything can happen. No one ever thinks it will until it does. What will happen, happens. That’s how the world is. The most important thing is to not let the tragedy defeat you. To believe that you can get through it.” – Kyousuke Natsume (Little Busters!)",
  "“You’ll only realize that you truly love someone if they already caused you enormous pain. Your enemies can never hurt you the way your loved ones can. It’s the people close to your heart that can give you the most piercing wound. Love is a double-edged sword, it can heal the wound faster or it can sink the blade even deeper.” – Himura Kenshin (Rurouni Kenshin)",
  "“I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.” – Kagome (InuYasha)",
  "“When you give up, that’s when the game ends.” – Mitsuyoshi Anzai (Slam Dunk)",
  "“All we can do is live until the day we die. Control what we can…and fly free.” – Deneil Young (Uchuu Kyoudai or Space Brothers)",
  "“Forgetting is like a wound. The wound may heal, but it has already left a scar.” – Monkey D. Luffy (One Piece)",
  "“It’s just pathetic to give up on something before you even give it a shot.” – Reiko Mikami (Another)",
  "“You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face.” – Roronoa Zoro (One Piece)",
  "“I too will obtain everything that I desire. Not because someone asked me to do it, but because I know in my heart that I have something worth fighting for.” – Julis Alexia Van Riessfeld (Asterisk War)",
  "“You can’t win a game by doing nothing. And if someone else wins it for you then you haven’t accomplished anything. Life is the same way.” – Junichirou Kagami (Denpa Kyoushi)",
  "“Do not think about other things, there is only one thing you can do. So master that one thing. Do not forget. What you must imagine is always that you, yourself, are the strongest. You do not need outside enemies. For you, the one you have to fight is none other than your own image.” – Archer (Fate Stay Night)",
  "“Life is like a tube of toothpaste. When you’ve used all the toothpaste down to the last squeeze, that’s when you’ve really lived. Live with all your might, and struggle as long as you have life.” – Mion Sonozaki (Higurashi)",
  "“Just like games, no matter how well you have things lined up in your life, there’s always something to keep you on your toes.” – Junichirou Kagami (Denpa Kyoushi)",
  "“Do exactly as you like. That is the true meaning of pleasure. Pleasure leads to joy and joy leads to happiness.” – Gilgamesh (Fate Zero)",
  "“If you wanna make people dream, you’ve gotta start by believing in that dream yourself!” – Seiya Kanie (Amagi Brilliant Park)",
  "“Being lonely is more painful then getting hurt.” – Monkey D. Luffy (One Piece)",
  "“There’s no shame in falling down! True shame is to not stand up again!” – Shintar? Midorima (Kuroko’s Basketball)",
  "“Simplicity is the easiest path to true beauty.” – Seishuu Handa (Barakamon)",
  "“If you can’t do something, then don’t. Focus on what you can.” – Shiroe (Log Horizon)",
  "“Giving up kills people. When people reject giving up… they finally win the right to transcend humanity.” – Alucard (Hellsing)",
  "“A dropout will beat a genius through hard work.” – Rock Lee (Naruto)",
  "“Reject common sense to make the impossible possible.” – Simon (Tengen Toppa Gurren Lagann)",
  "“Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.” – Kenshin Himura (Rurouni Kenshin: Meiji Kenkaku Romantan)",
  "“If you really want to be strong… Stop caring about what your surrounding thinks of you!” – Saitama (One Punch Man)",
  "“Vision is not what your eyes see, but an image that your brain comprehends.” – Touko Aozaki (The Garden of Sinners / Kara no Ky?kai)",
  "“Sometimes, people are just mean. Don’t fight mean with mean. Hold your head high.” – Hinata Miyake (A Place Further than the Universe)",
  "“The ticket to the future is always open.” – Vash The Stampede (Trigun)",
  "“Hard work is worthless for those that don’t believe in themselves.” – Naruto Uzumaki (Naruto)",
  "“A place where someone still thinks about you is a place you can call home.” – Jiraiya (Naruto)",
  "“Life comes at a cost. Wouldn’t it be arrogant to die before you’ve repaid that debt?” – Yuuji Kazami (The Fruit of Grisaia / Gurizaia no Kajitsu)",
  "“You can die anytime, but living takes true courage.” – Himura Kenshin (Rurouni Kenshin)",
  "“Every journey begins with a single step. We just have to have patience.” – Milly Thompson (Trigun)",
  "“If you just submit yourself to fate, then that’s the end of it.” – Keiichi Maebara (Higurashi: When They Cry)",
  "“There are no regrets. If one can be proud of one’s life, one should not wish for another chance.” – Saber (Fate Stay Night)",
  "“If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.” – Naruto Uzumaki (Naruto)",
  "“Don’t beg for things. Do it yourself, or else you won’t get anything.” – Renton Thurston (Eureka Seven)",
  "“I refuse to let my fear control me anymore.” – Maka Albarn (Soul Eater)",
  "“If you can’t find a reason to fight, then you shouldn’t be fighting.” – Akame (Akame Ga Kill)",
  "“You should never give up on life, no matter how you feel. No matter how badly you want to give up.” – Canaan",
  "“People who can’t throw something important away, can never hope to change anything.” – Armin Arlelt (Attack on Titan)",
  "“We can’t waste time worrying about the what if’s.” – Ichigo Kurosaki (Bleach)",
  "“Fools who don’t respect the past are likely to repeat it.” – Nico Robin (One Piece)",
  "“That’s why I can’t make a change. Everything I do is so… Half-assed.” – Hiroshi Kido (Barakamon)",
  "“Sometimes it’s necessary to do unnecessary things.” – Kanade Jinguuji (Best Student Council)",
  "“An excellent leader must be passionate because it’s their duty to keep everyone moving forward.” – Nico Yazawa (Love Live)",
  "“Protecting someone means giving them a place to belong. Giving them a place where they can be happy.” – Princess Lenessia (Log Horizon)",
  "“Thinking you’re no-good and worthless is the worst thing you can do” – Nobito (Doraemon)",
  "“Sometimes I do feel like I’m a failure. Like there’s no hope for me. But even so, I’m not gonna give up. Ever!” – Izuku Midoriya (My Hero Academia)",
  "“If you can’t do something, then don’t. Focus on what you can do.” – Shiroe (Log Horizon)",
  "“When you lose sight of your path, listen for the destination in your heart.” – Allen Walker (D.Gray Man)",
  "“The moment you think of giving up, think of the reason why you held on so long.” – Natsu Dragneel (Fairy Tail)",
  "“Don’t give up, there’s no shame in falling down! True shame is to not stand up again!” – Shintaro Midorima (Kuroko No Basket)",
  "“No matter how hard or impossible it is, never lose sight of your goal.” – Monkey D Luffy (One Piece)",
  "“Life is not a game of luck. If you wanna win, work hard.” – Sora (No Game No Life)",
  "“The world isn’t perfect. But it’s there for us, doing the best it can….that’s what makes it so damn beautiful.” – Roy Mustang (Full Metal Alchemist)",
  "“Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.” – Gildarts Clive (Fairy Tail)",
  "“To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.” – Matsumoto Rangiku (Bleach)",
  "“Knowing you’re different is only the beginning. If you accept these differences you’ll be able to get past them and grow even closer.” – Miss Kobayashi (Dragon Maid)",
  "“Don’t be so quick to throw away your life. No matter how disgraceful or embarrassing it may be, you need to keep struggling to find your way out until the very end.” – Clare (Claymore)",
  "“The world’s not perfect, but it’s there for us trying the best it can. That’s what makes it so damn beautiful.” – Roy Mustang (Fullmetal Alchemist)",
  "“We are all like fireworks: we climb, we shine and always go our separate ways and become further apart. But even when that time comes, let’s not disappear like a firework and continue to shine.. forever.” – Hitsugaya Toshiro (Bleach)",
  "“You can die anytime, but living takes true courage.” – Kenshin Himura",
  "“Every journey begins with a single step. We just have to have patience.” – Milly Thompson",
  "“It doesn’t do any good to pretend you can’t see what’s going on.” – Yuuya Mochizuki (Another)",
  "“Being weak is nothing to be ashamed of… Staying weak is !!” – Fuegoleon Vermillion (Black Clover)",
  "“To act is not necessarily compassion. True compassion sometimes comes from inaction.” – Hinata Miyake (A Place Further than the Universe)",
  "“If nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas.” – Alibaba Saluja (Magi)",
  "“When you hit the point of no return, that’s the moment it truly becomes a journey. If you can still turn back, it’s not really a journey.” – Hinata Miyake (A Place Further than the Universe)",
  "“Those who stand at the top determine what’s wrong and what’s right! This very place is neutral ground! Justice will prevail, you say? But of course it will! Whoever wins this war becomes justice!” – Don Quixote Doflamingo (One Piece)",
  "“A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.“ – Jiraiya (Naruto)",
  "“Who decides limits? And based on what? You said you worked hard? Well, maybe you need to work a little harder. Is that really the limit of your strength? Could you of tomorrow beat you today? Instead of giving in, move forward.” – Saitama (One Punch Man)",
  "“Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.” – Mavis Vermillion (Fairy Tail)",
  "“Fear is freedom! Subjugation is liberation! Contradiction is the truth! Those are the facts of this world! And you will all surrender to them, you pigs in human clothing!” – Satsuki Kiryuuin (Kill la Kill)",
  "“Hatred and Sorrow are power. They are yours to control. All you have to do is to turn them into strength and use that strength to move forward.“ – Sebastian Michaelis (Black Butler / Kuroshitsuji)",
  "“It’s not always possible to do what we want to do, but it’s important to believe in something before you actually do it.” – Might Guy (Naruto)",
  "“Life and death are like light and shadow. They’re both always there. But people don’t like thinking about death, so subconsciously, they always look away from it.” – Yato (Noragami)",
  "“It’s more important to master the cards you’re holding than to complain about the ones your opponent was dealt.” – Grimsley (Pokemon)",
  "“I am the hope of the universe. I am the answer to all living things that cry out for peace. I am the protector of the innocent. I am the light in the darkness. I am the truth. Ally to good! Nightmare to you!” – Son Goku (Dragon Ball Z)",
  "“If you’re gonna insist on gambling and then complain when you lose, you had better work on your game.” – Hatsu Kominato (Selector Infected Wixoss)",
  "“Moving on doesn’t mean you forget about things. It just means you have to accept what’s happened and continue living.“ – Erza Scarlet (Fairy Tail)",
  "“If nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas.” – Alibaba Saluja (Universal Warriors)",
  "“If you keep on hiding your true feelings, who is going to be happy? If you are sad, you should say it out loud!” – Haruhi Fujioka (Ouran High School Host Club)",
  "“Religion, ideology, resources, land, spite, love or just because… No matter how pathetic the reason, it’s enough to start a war. War will never cease to exist… reasons can be thought up after the fact… Human nature pursues strife.” – Paine (Naruto Shippuden)",
  "“It is at the moment of death that humanity has value.” – Archer (Fate Series)",
  "“People, who can’t throw something important away, can never hope to change anything.” – Armin Arlert (Shingeki no Kyojin / Attack on Titan)",
  "“Whatever you do, enjoy it to the fullest. That is the secret of life.” – Rider (Fate Zero)",
  "“Power comes in response to a need, not a desire. You have to create that need.” – Goku (Dragon Ball Z)",
  "“Don’t be upset because of what you can’t do. Do what you do best, live as carefree and optimistically as you can, because some people aren’t able to do that.” – Keima Katsuragi (The World God Only Knows)",
  "“If you begin to regret, you’ll dull your future decisions and let others make your choices for you. All that’s left for you then is to die. Nobody can foretell the outcome. Each decision you make holds meaning only by affecting your next decision.” – Erwin Smith (Attack on Titan)"
];


export default function handler(req, res) {
  // Only allow GET requests
  if (req.method !== 'GET') {
    return res.status(405).send('Method Not Allowed');
  }

  // Get a random quote
  const randomIndex = Math.floor(Math.random() * animeQuotes.length);
  const randomQuote = animeQuotes[randomIndex];

  // Return as JSON
  res.status(200).json({ message: randomQuote });
}
